# Exported from:        http://dhivya:5516/
# Release version:      26.1.0-SNAPSHOT
# Date created:         Mon Nov 24 14:53:15 IST 2025

---
apiVersion: xl-release/v1
kind: Environments
metadata:
  path: /
  home: tesst
spec:
- name: test
  type: xlrelease.Environment
  stage: Test
