# Exported from:        http://dhivya:5516/
# Release version:      26.1.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Environments
metadata:
  path: /
  home: test
spec:
- name: test
  type: xlrelease.Environment
  stage: Test
